#! /usr/bin/env node

try {
  var testing = require('./async_testing');
}
catch(err) {
  if( err.message == "Cannot find module './async_testing'" ) {
    var testing = require('async_testing');
  }
  else {
    throw err;
  }
}

testing.run(null, process.ARGV);
