#! /usr/bin/env node

try {
  var testing = require('./async_testing');
}
catch(err) {
  if( err.message == "Cannot find module './async_testing'" ) {
    var testing = require('async_testing');
  }
  else {
    throw err;
  }
}

testing.run(null, process.ARGV, done);

function done(allResults) {
  var problems = 0;

  for(var i = 0; i < allResults.length; i++) {
    if (allResults[i].tests.length > 0) {
      problems += allResults[i].numErrors;
      problems += allResults[i].numFailures;
    }
  }

  process.exit(problems);
}
